// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2lJtb_U45e1ImZqu8vjpea3xGJv_3868',
    appId: '1:188841892955:web:a546bcb914a77f94e5337e',
    messagingSenderId: '188841892955',
    projectId: 'centranews-21bfe',
    authDomain: 'centranews-21bfe.firebaseapp.com',
    storageBucket: 'centranews-21bfe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPCLPhGRVsPBBSp9a7oXHcZxKDERARKvE',
    appId: '1:188841892955:android:9ff6e34c3f865816e5337e',
    messagingSenderId: '188841892955',
    projectId: 'centranews-21bfe',
    storageBucket: 'centranews-21bfe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUJ5htsdVRfAlP5yp0YO509DzPc2SN9K0',
    appId: '1:188841892955:ios:29dbb95d283a6d70e5337e',
    messagingSenderId: '188841892955',
    projectId: 'centranews-21bfe',
    storageBucket: 'centranews-21bfe.firebasestorage.app',
    iosBundleId: 'com.example.centranews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUJ5htsdVRfAlP5yp0YO509DzPc2SN9K0',
    appId: '1:188841892955:ios:29dbb95d283a6d70e5337e',
    messagingSenderId: '188841892955',
    projectId: 'centranews-21bfe',
    storageBucket: 'centranews-21bfe.firebasestorage.app',
    iosBundleId: 'com.example.centranews',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2lJtb_U45e1ImZqu8vjpea3xGJv_3868',
    appId: '1:188841892955:web:c10e99ace2f55d74e5337e',
    messagingSenderId: '188841892955',
    projectId: 'centranews-21bfe',
    authDomain: 'centranews-21bfe.firebaseapp.com',
    storageBucket: 'centranews-21bfe.firebasestorage.app',
  );

}